Repository prab33n/Explore-Unexplored-Nepal, pull requests merged in 2024-10, with the labels that each got.

#5 Galyang Aalam Devi Mandir added
  Data.json
Labels: good first issue, Hacktoberfest2024 accepted

#8 New commit
  Data.json
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted

#9 accepted
  Data.json
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted

#16 data: added amazing places to visit in the Rupandehi district
  src/data/exploreNepalData.js
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted, hacktoberfestaccepted

#18 Bearhill added
  Data.json
Labels: Hacktoberfest2024 accepted, hacktoberfestaccepted

#22 dark-mode-toggle
  src/App.jsx
  src/components/Filter.jsx
Labels: good first issue, Hacktoberfest2024, Hacktoberfest2024 accepted, hacktoberfestaccepted

#23 data: added more places to visit in the Rupandehi district
  src/data/exploreNepalData.js
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted, hacktoberfestaccepted

#29 gmc added
  Data.json
Labels: Hacktoberfest2024, hacktoberfestaccepted

#30 Bagmati Province data added
  Data.json
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted, hacktoberfestaccepted

#59 Mangal Momo House
  Data.json
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted, hacktoberfestaccepted

#62 kd added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted, hacktoberfestaccepted

#69 Tourism place of Taplejung
  public/Images/pathivara.jpg
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024, Hacktoberfest2024 accepted

#87 Simalchaur Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024 accepted

#89 Darsing Cave Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024

#88 Data of Jhapa district added
  public/Images/kankai.jpg
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024 accepted

#92 Kharel Danda Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024 accepted

#91 Majuwa Waterfall Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024 accepted

#93 Sirsekot Baghdurgar Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024 accepted

#121 Kotihawa Stupa Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024 accepted

#128 Kaligandaki River Bank Added
  src/data/exploreNepalData.json
Labels: Hacktoberfest2024
